steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["run", "build"]
  - name: gcr.io/buildpacks/builder
    args: ["cd", "build"]
  - name: gcr.io/buildpacks/builder
    args:
      [
        "pack",
        "build",
        "gcr.io/radiant-oven-362122/github.com/areaewhy/lunchbox:$COMMIT_SHA",
      ]
